### ISSUE TITLE
option to pass "gs" url in `reviewer.run()`

### ISSUE THREAD

**Issue by cetienn01** [getzlab/AnnoMate#16]
is it possible to add an option to pass a `gs` url to automatically store the data into a google bucket directly (when you run the reviewer)? (Example: `auto_export_path = "gs://<path_to_google_bucket>"`)

```
# run the PurityReviewer
matched_reviewer.run(
    ...
    auto_export_path = 'gs://<path_to_google_bucket>'
)
```
- currently all the output is stored locally:
```
  if not os.path.exists(auto_export_path):
      print(f'Making directory {auto_export_path} for auto exporting.')
      os.mkdir(auto_export_path)
```

**other option:**
i know that one option is to manually upload the output within a separate cell inside the jupyter notebook `AFTER` running the reviewer:
```
reviewer.run()
…
reviewer.get_annot().to_csv("gs://path/to/save/annot_df.tsv", sep='\t')
reviewer.get_history().to_csv("gs://path/to/save/history_df.tsv", sep='\t')
```
but it would be great to be able to add that in the `run()` itself

**Comment by cchu70** [comment]
https://github.com/getzlab/AnnoMate/pull/20
