### ISSUE TITLE
option to include `inline=True()` when displaying "annotation components"

### ISSUE THREAD

**Issue by cetienn01** [getzlab/AnnoMate#17]
could we have an option to display annotation components inline when running the notebook?
Specifically, can we update all the annotation display components to take `**kwargs` so that we can pass "inline=True"?

-- example: [AnnotationDisplayComponent.py](https://github.com/getzlab/AnnoMate/blob/bb3cb7e45d0fd6f2a41221b941fd686da872bd38/AnnoMate/AnnotationDisplayComponent.py)
```
def gen_input_component(self, data_annot: DataAnnotation, component_id: str, **kwargs):
        return dbc.Checklist(
            options=[{"label": f, "value": f} for f in data_annot.options],
            id=component_id, 
            value='' if self.default_display_value is None else self.default_display_value # Checklist does not take NoneType values,
           **kwargs
        )
``` 
for reference: https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/

**Comment by cchu70** [comment]
https://github.com/getzlab/AnnoMate/pull/20
